#! /bin/bash

#Tablet Pad Settings...
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "Button" "1" "key +Escape "
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "Button" "2" "button +2 "
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "Button" "3" "key +Control_L "
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "Button" "8" "key +Control_L +space "
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "Button" "9" "key +Shift_L +space "
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "ToolDebugLevel" "0"
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "TabletDebugLevel" "0"
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "Suppress" "2"
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "RawSample" "4"
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "Mode" "Absolute"
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "Touch" "off"
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "Gesture" "off"
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "ZoomDistance" "0"
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "ScrollDistance" "0"
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "TapTime" "250"
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "RelWheelUp" "1" "button +5 "
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "RelWheelDown" "2" "button +4 "
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "AbsWheelUp" "3" "button +4 "
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "AbsWheelDown" "4" "button +5 "
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "AbsWheel2Up" "5" "button +4 "
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "AbsWheel2Down" "6" "button +5 "
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "StripLeftUp" "1" "button +4 "
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "StripLeftDown" "2" "button +5 "
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "StripRightUp" "3" "button +4 "
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "StripRightDown" "4" "button +5 "
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "Threshold" "0"
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "BindToSerial" "0"
xsetwacom set "Wacom Bamboo 16FG 4x5 Pad pad" "PanScrollThreshold" "13"
